# Generated by Django 6.0 on 2026-05-24 19:21

import cloudinary.models
import cloudinary_storage.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.PositiveIntegerField()),
                ('work_date', models.DateField()),
                ('work_performed', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternshipPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('max_applicants', models.PositiveIntegerField(blank=True, null=True)),
                ('working_days', models.JSONField(blank=True, default=list, help_text='List of weekday names, e.g. ["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY"]')),
                ('daily_start_time', models.TimeField(blank=True, null=True)),
                ('daily_end_time', models.TimeField(blank=True, null=True)),
                ('work_mode', models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'Onsite'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=10)),
                ('is_remote', models.BooleanField(default=False)),
                ('work_latitude', models.FloatField(blank=True, null=True)),
                ('work_longitude', models.FloatField(blank=True, null=True)),
                ('allowed_radius_meters', models.PositiveIntegerField(default=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyIndustryEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_number', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted by Company'), ('ADVISOR_APPROVED', 'Approved by Advisor'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('advisor_approved_at', models.DateTimeField(blank=True, null=True)),
                ('advisor_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('visible_to_student', models.BooleanField(default=False)),
                ('work_quality_score', models.PositiveIntegerField(default=0)),
                ('punctuality_score', models.PositiveIntegerField(default=0)),
                ('attitude_score', models.PositiveIntegerField(default=0)),
                ('initiative_score', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('total_score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Monthly Industry Evaluation',
                'verbose_name_plural': 'Monthly Industry Evaluations',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INTERNSHIP_STATUS_CHANGED', 'Internship Status Changed'), ('REPORT_SUBMITTED', 'Report Submitted'), ('REPORT_REVIEWED', 'Report Reviewed'), ('GENERAL', 'General')], default='GENERAL', max_length=40)),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OverallInternshipEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('examiner_average_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('company_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('final_total_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('final_grade', models.CharField(blank=True, max_length=5)),
                ('status', models.CharField(choices=[('PENDING_ADVISOR', 'Pending Advisor'), ('PENDING_EXAMINERS', 'Pending Examiners'), ('PENDING_COORDINATOR', 'Pending Coordinator'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_ADVISOR', max_length=30)),
                ('advisor_approved', models.BooleanField(default=False)),
                ('examiner_completed', models.BooleanField(default=False)),
                ('coordinator_approved', models.BooleanField(default=False)),
                ('advisor_approved_at', models.DateTimeField(blank=True, null=True)),
                ('examiner_completed_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator_approved_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator_comment', models.TextField(blank=True)),
                ('visible_to_student', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreRegisteredStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REVIEWED', 'Reviewed')], default='DRAFT', max_length=20)),
                ('student_comment', models.TextField(blank=True)),
                ('company_comment', models.TextField(blank=True)),
                ('advisor_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='advisorevaluation',
            options={'verbose_name': 'Advisor Evaluation', 'verbose_name_plural': 'Advisor Evaluations'},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='hours_worked',
            new_name='total_hours',
        ),
        migrations.RemoveField(
            model_name='advisorevaluation',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='advisorevaluation',
            name='evaluation_date',
        ),
        migrations.RemoveField(
            model_name='advisorevaluation',
            name='score',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='application_date',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reportfile',
            name='file_path',
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='activities_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='conclusion_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='daily_detail_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='data_figure_table_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='discipline_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='engagement_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='final_weighted_mark',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='improvement_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='initiative_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='logbook_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='organization_background_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='pictures_and_data_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='recommendation_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='report_content_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='report_format_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='report_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='student_performance_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='understanding_objective_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='weekly_summary_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='weighted_logbook_mark',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='weighted_report_mark',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='advisorevaluation',
            name='weighted_student_performance_mark',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_location_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preregisteredstudent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preregisteredstudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='advisor_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='advisor_comment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='advisor_comment_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor_commented_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='examiner_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='examiner_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='examiner_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner_reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='final_reports/'),
        ),
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='student',
            name='resume_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advisorevaluation',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_advisor_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], default='PRESENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='companymentor',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to='core.company'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='communication_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='overall_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='problem_solving_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='professionalism_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='technical_skills_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='core.company'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.companymentor'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='internship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supervisor'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted by Student'), ('EXAMINER_APPROVED', 'Approved by Examiner'), ('EXAMINER_REJECTED', 'Rejected by Examiner'), ('ADVISOR_APPROVED', 'Approved by Advisor'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('internship', 'date')},
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisors', to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='core.advisor'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalIndustryEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted by Company'), ('ADVISOR_APPROVED', 'Approved by Advisor'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('advisor_approved_at', models.DateTimeField(blank=True, null=True)),
                ('advisor_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('visible_to_student', models.BooleanField(default=False)),
                ('knowledge_about_task', models.PositiveIntegerField(default=0)),
                ('problem_solving', models.PositiveIntegerField(default=0)),
                ('quality_of_work', models.PositiveIntegerField(default=0)),
                ('punctuality_in_production', models.PositiveIntegerField(default=0)),
                ('initiative', models.PositiveIntegerField(default=0)),
                ('dedication', models.PositiveIntegerField(default=0)),
                ('cooperation', models.PositiveIntegerField(default=0)),
                ('discipline', models.PositiveIntegerField(default=0)),
                ('responsibility', models.PositiveIntegerField(default=0)),
                ('socialization', models.PositiveIntegerField(default=0)),
                ('communication', models.PositiveIntegerField(default=0)),
                ('decision_making', models.PositiveIntegerField(default=0)),
                ('student_potential', models.TextField(blank=True)),
                ('overall_comments', models.TextField(blank=True)),
                ('would_offer_job', models.BooleanField(default=False)),
                ('section_a_total', models.PositiveIntegerField(default=0)),
                ('section_b_total', models.PositiveIntegerField(default=0)),
                ('total_mark', models.PositiveIntegerField(default=0)),
                ('overall_student_performance', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('advisor_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_final_industry_evaluations', to=settings.AUTH_USER_MODEL)),
                ('company_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_evaluations', to='core.companymentor')),
                ('internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_industry_evaluation', to='core.internship')),
            ],
            options={
                'verbose_name': 'Final Industry Evaluation',
                'verbose_name_plural': 'Final Industry Evaluations',
            },
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dept_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('mentor_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=20, null=True)),
                ('student_decision', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('advisor_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('advisor_notes', models.TextField(blank=True)),
                ('requested_start_date', models.DateField(blank=True, null=True)),
                ('requested_end_date', models.DateField(blank=True, null=True)),
                ('working_days_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('working_hours_per_day', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('form_snapshot', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.TextField(blank=True)),
                ('coordinator_signature', models.CharField(blank=True, max_length=255)),
                ('coordinator_signed_at', models.DateTimeField(blank=True, null=True)),
                ('mentor_signature', models.CharField(blank=True, max_length=255)),
                ('mentor_signed_at', models.DateTimeField(blank=True, null=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to='core.advisor')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.companymentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.student')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('technical_skills_score', models.PositiveIntegerField(default=0)),
                ('communication_score', models.PositiveIntegerField(default=0)),
                ('professionalism_score', models.PositiveIntegerField(default=0)),
                ('report_quality_score', models.PositiveIntegerField(default=0)),
                ('presentation_score', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('weighted_score', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('examiner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_examiner_evaluations', to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiner_evaluations', to='core.internshipapplication')),
            ],
            options={
                'verbose_name': 'Examiner Evaluation',
                'verbose_name_plural': 'Examiner Evaluations',
            },
        ),
        migrations.AlterField(
            model_name='advisorassignment',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_assignments', to='core.internshipapplication'),
        ),
        migrations.AlterField(
            model_name='advisorevaluation',
            name='internship',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_evaluation', to='core.internshipapplication'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.internshipapplication'),
        ),
        migrations.AlterField(
            model_name='report',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.internshipapplication'),
        ),
        migrations.AddConstraint(
            model_name='advisorevaluation',
            constraint=models.UniqueConstraint(fields=('internship',), name='unique_advisor_evaluation_per_internship'),
        ),
        migrations.AddField(
            model_name='internshipposition',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_positions', to='core.company'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.internshipposition'),
        ),
        migrations.AddField(
            model_name='internship',
            name='position',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='core.internshipposition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyindustryevaluation',
            name='advisor_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_monthly_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyindustryevaluation',
            name='company_mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_evaluations', to='core.companymentor'),
        ),
        migrations.AddField(
            model_name='monthlyindustryevaluation',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_industry_evaluations', to='core.internshipapplication'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overallinternshipevaluation',
            name='advisor_evaluation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.advisorevaluation'),
        ),
        migrations.AddField(
            model_name='overallinternshipevaluation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_overall_evals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overallinternshipevaluation',
            name='company_evaluation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.finalindustryevaluation'),
        ),
        migrations.AddField(
            model_name='overallinternshipevaluation',
            name='examiner_one_evaluation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overall_eval_one', to='core.examinerevaluation'),
        ),
        migrations.AddField(
            model_name='overallinternshipevaluation',
            name='examiner_two_evaluation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overall_eval_two', to='core.examinerevaluation'),
        ),
        migrations.AddField(
            model_name='overallinternshipevaluation',
            name='internship',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overall_evaluation', to='core.internshipapplication'),
        ),
        migrations.AddField(
            model_name='preregisteredstaff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internshipposition',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='internship_positions', to='core.skill'),
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logbooks', to='core.internshipapplication'),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supervisor'),
        ),
        migrations.AddField(
            model_name='weeklylogbook',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.companymentor'),
        ),
        migrations.AddField(
            model_name='dailylogentry',
            name='weekly_logbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='core.weeklylogbook'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor'], name='core_auditl_actor_i_870709_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='finalindustryevaluation',
            unique_together={('internship',)},
        ),
        migrations.AddConstraint(
            model_name='examinerevaluation',
            constraint=models.UniqueConstraint(fields=('internship', 'examiner'), name='unique_examiner_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='examinerevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('communication_score__gte', 0), ('communication_score__lte', 5), ('presentation_score__gte', 0), ('presentation_score__lte', 5), ('professionalism_score__gte', 0), ('professionalism_score__lte', 5), ('report_quality_score__gte', 0), ('report_quality_score__lte', 5), ('technical_skills_score__gte', 0), ('technical_skills_score__lte', 5)), name='examiner_eval_scores_range'),
        ),
        migrations.AlterUniqueTogether(
            name='internshipapplication',
            unique_together={('student', 'position')},
        ),
        migrations.AddConstraint(
            model_name='monthlyindustryevaluation',
            constraint=models.UniqueConstraint(fields=('internship', 'month_number'), name='unique_monthly_eval_per_internship_month'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipposition',
            index=models.Index(fields=['company', 'is_active'], name='core_intern_company_94c7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='internshipposition',
            index=models.Index(fields=['application_deadline'], name='core_intern_applica_21f578_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklylogbook',
            constraint=models.UniqueConstraint(fields=('internship', 'week_number'), name='unique_weekly_logbook'),
        ),
    ]
