# Generated by Django 6.0 on 2026-05-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_selfplacementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
