# Generated by Django 6.0 on 2026-05-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_form_data_to_company_evals'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregisteredstudent',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
