# Generated by Django 6.0 on 2026-06-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_examiner_approval_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='overallinternshipevaluation',
            name='company_final_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='overallinternshipevaluation',
            name='company_monthly_avg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
